name: "alles im fluss&#8230; &bull; bleibt neugierig!"
markdown: kramdown
highlighter: pygments
permalink: /:year/:month/:day/:title/
url: http://blog.rh-flow.de
#url: http://ronnyhartenstein.github.io
baseurl:
excerpt_separator: <!--more-->
gems:
  - jemoji
